### ISSUE TITLE
How to import data back from json file in the zip to MongoDB in meteor.js?

### ISSUE THREAD

**Issue by phirum** [themeteorchef/exporting-data-from-your-meteor-application#4]
I want to import the data back form the files.
 How can import data back from json file in the zip to MongoDB in meteor.js?

**Comment by themeteorchef** [comment]
Hey, @phirum, good question. This requires a few additional steps. You will need to add a file input within a form and then process that input on the server to insert it into the database (that's pretty vague, but the full answer is worthy of a separate post). 

I'll likely cover this in a separate recipe at some point. For now, I would take a look at this example of uploading files as it may give you a hint about what you need to do (this is for a .csv file, not json): https://github.com/Ajaxsoap/meteor-sample-csv-importer.
